version: '3.9'

services:
  app:
    build: ..
    ports:
      - "8001:8000"
    volumes:
      - C:\Users\VARTAN\Desktop\documents:\documents
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    depends_on:
      - db
      - rabbitmq

  db:
    container_name: db_app
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: project1
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3.9-alpine
    container_name: rabbitmq_app
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 10
    ports:
      - "5672:5672"
      - "15672:15672"

  celery:
    build: ..
    command: celery -A celery_worker:app worker --loglevel=info
    volumes:
      - C:\\Users\\VARTAN\\Desktop\\documents:\documents
    depends_on:
      - rabbitmq
      - db
