"""Название вашей миграции

Revision ID: 5b61aa567977
Revises: 
Create Date: 2024-06-24 02:39:39.570667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b61aa567977'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Document',
    sa.Column('id_Document', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('psth', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id_Document')
    )
    op.create_table('Document_text',
    sa.Column('id_Document_text', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('id_Document', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_Document'], ['Document.id_Document'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_Document_text')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Document_text')
    op.drop_table('Document')
    # ### end Alembic commands ###
